/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { RpcGo } from "./RpcGo";

export { ERC20__factory } from "./factories/ERC20__factory";
export { RpcGo__factory } from "./factories/RpcGo__factory";
