/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface RpcInterface extends ethers.utils.Interface {
  functions: {
    "submitTransaction(address,uint256,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "submitTransaction",
    values: [string, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "submitTransaction",
    data: BytesLike
  ): Result;

  events: {
    "ExecuteTransaction(address,address,uint256,bytes)": EventFragment;
    "LogData(bytes)": EventFragment;
    "RevertReason(string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ExecuteTransaction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogData"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RevertReason"): EventFragment;
}

export type ExecuteTransactionEvent = TypedEvent<
  [string, string, BigNumber, string] & {
    from: string;
    to: string;
    _value: BigNumber;
    _data: string;
  }
>;

export type LogDataEvent = TypedEvent<[string] & { data: string }>;

export type RevertReasonEvent = TypedEvent<[string] & { reason: string }>;

export class Rpc extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RpcInterface;

  functions: {
    submitTransaction(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  submitTransaction(
    _to: string,
    _value: BigNumberish,
    _data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    submitTransaction(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ExecuteTransaction(address,address,uint256,bytes)"(
      from?: string | null,
      to?: string | null,
      _value?: null,
      _data?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string],
      { from: string; to: string; _value: BigNumber; _data: string }
    >;

    ExecuteTransaction(
      from?: string | null,
      to?: string | null,
      _value?: null,
      _data?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string],
      { from: string; to: string; _value: BigNumber; _data: string }
    >;

    "LogData(bytes)"(data?: null): TypedEventFilter<[string], { data: string }>;

    LogData(data?: null): TypedEventFilter<[string], { data: string }>;

    "RevertReason(string)"(
      reason?: null
    ): TypedEventFilter<[string], { reason: string }>;

    RevertReason(reason?: null): TypedEventFilter<[string], { reason: string }>;
  };

  estimateGas: {
    submitTransaction(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    submitTransaction(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
